config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :expenses
  resources :incomes
  resources :users

  root "static_pages#home"

  get 'home' => 'static_pages#home'
  get 'signup'  => 'users#new'
  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/report' => 'reports#report', as: :report

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index

  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_navigation.html.erb
<div class="nav pull-right">
  <% if current_user %>
      <ul>
        <li><%= current_user.email %></li>
        <li class="item"><%= link_to "Expenses", expenses_path %></li>
        <li class="item"><%= link_to "Incomes", incomes_path %></li>
        <li class="item"><%= link_to "Categories", categories_path %></li>
        <li class="item"><%= link_to "Reports", report_path %></li>
        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      </ul>
  <% else %>
      <ul>
        <li><%= link_to "Login", 'login'%></a></li>
        <li><%= link_to "Signup", 'signup' %></a></li>
      </ul>
  <% end %>
</div>

app/views/static_pages/about.html.erb
<h1>About</h1>

<p>
  That is easy application which helps you to manage your incomes and expanses!
</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>How to use this application?</p>
<p>It is easy to find out it from the first view. Here is a list of capabilities you able to do after you log in. You can:</p>
<ul>
  <li>Add/edit/remove your income notes</li>
  <li>Add/edit/remove expense notes</li>
  <li>Get report about you income and expense by date period</li>
</ul>

app/views/static_pages/home.html.erb
<% unless current_user %>
<div class="container">
      <h1>Welcome to calculator of your incomes and expenses</h1>
      <h2>Sign up or Login to account</h2>
      <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
      <%= link_to "Login", 'login', class: "btb btn-lg btn-primary"%>
</div>
<% end %>

<% if current_user %>
    <h2>Hello, <%= current_user.email %></h2>
<% end %>