config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :expenses
  resources :incomes
  resources :users

  root "static_pages#home"

  get 'home' => 'static_pages#home'
  get 'signup'  => 'users#new'
  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/report' => 'reports#report', as: :report

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Calculator Application
    by <a href="https://github.com/andreydro">Dro</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class ="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Calculator", "#" , id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "Home", home_path %></li>
        <li> <%= link_to "Help", help_path %></li>
        <li> <%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PurseApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
        <%= render 'layouts/header' %>

        <%= render 'static_pages/navigation'%>

        <%= yield %>

        <%= render 'layouts/footer' %>
    </div>
</body>
</html>